// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BaseModel interface {
	IsBaseModel()
	GetID() string
	GetName() string
	GetSlug() *string
}

type SearchRecipeResult interface {
	IsSearchRecipeResult()
}

type NewIngredient struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Quantity string `json:"quantity"`
}

type NewRecipe struct {
	Name        string           `json:"name"`
	Timers      []string         `json:"timers"`
	Steps       []string         `json:"steps"`
	ImageURL    string           `json:"imageURL"`
	OriginalURL string           `json:"originalURL"`
	Ingredients []*NewIngredient `json:"ingredients"`
}

type PaginationData struct {
	Total     int `json:"total"`
	Page      int `json:"page"`
	PerPage   int `json:"perPage"`
	Prev      int `json:"prev"`
	Next      int `json:"next"`
	TotalPage int `json:"totalPage"`
}

type UpdateIngredient struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	Quantity string `json:"quantity"`
}

type UpdateRecipe struct {
	ID          string              `json:"id"`
	Name        string              `json:"name"`
	Timers      []string            `json:"timers"`
	Steps       []string            `json:"steps"`
	ImageURL    string              `json:"imageURL"`
	OriginalURL string              `json:"originalURL"`
	Ingredients []*UpdateIngredient `json:"ingredients"`
}
